disabled_rules:
- trailing_whitespace
- unused_setter_value
- private_over_fileprivate

identifier_name:
  severity: warning
  min_length: 2 # only warning
  max_length: 60 # warning
  excluded: # excluded via string array
    - id
    - URL
  validates_start_with_lowercase: true

function_parameter_count:
  warning: 7
  error: 10
  
line_length:
  warning: 150
  error: 250
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  
type_body_length:
  - 400 # warning
  - 600 # error
  
function_body_length:
  - 60 # warning
  - 100 # error
  
type_name:
    min_length: 2
    max_length: 50
#  warning: 50
#  error: 70
#  - 50 # warning
#  - 70 # error

file_length:
  warning: 500
  error: 700
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
