# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IceHockey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IceHockey
  pod 'FirebaseUI'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/DynamicLinks'

  pod 'GoogleSignIn'

  #pod 'FirebaseUI'
  #pod 'FirebaseUI/Google'
  #pod 'FirebaseUI/Facebook'
  #pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc

  pod 'SwiftGen', '~> 6.0'

  pod 'SwiftLint'

end
